ci: Don't bail on warnings from -Wcast-qual
Some of our dependencies may cause bad casts, e.g. older GLib's definition
of g_utf8_next_char() has a useless cast to (char *):

```
../../chafa/chafa-symbol-map.c: In function 'parse_selectors':
/usr/include/glib-2.0/glib/gunicode.h:809:29: error: cast discards 'const' qualifier from pointer target type [-Werror=cast-qual]
  809 | #define g_utf8_next_char(p) (char *)((p) + g_utf8_skip[*(const guchar *)(p)])
      |                             ^
../../chafa/chafa-symbol-map.c:972:37: note: in expansion of macro 'g_utf8_next_char'
  972 |             for ( ; p0 && *p0; p0 = g_utf8_next_char (p0))
      |                                     ^~~~~~~~~~~~~~~~
```